### ISSUE TITLE
Case sensitivity of table name

### ISSUE THREAD

**Issue by uiii** [LostKobrakai/Migrations#12]
I ran into an issue with `Migrations` table name. I've installed the migrations module in windows and then upload the database to production site on Linux server. The table was named `migrations` (first letter lowercase), which causes an error with missing table. According to this document http://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html mysql handles the case sensitivity differently depending on underlying operating system. I think it would be best to explicitly use lowercase table name.

**Comment by LostKobrakai** [comment]
Good point, seems like I did copy that part from another module and not the core, where table names are already all lowercase.
