### ISSUE TITLE
error when creating migration with processwire 3.0.61 / PHP 5.5.9

### ISSUE THREAD

**Issue by westhom** [LostKobrakai/Migrations#16]
When creating a new migration through the admin panel I get this error:

`Error: Call to undefined function wirePopulateStringTags() (line 70 of site/modules/Migrations/Migrations.module)`

Was able to get around it by changing the function call to `ProcessWire\wirePopulateStringTags(`

**Comment by LostKobrakai** [comment]
Did you disable the file compiler? That file should get compiled to prepend the namespace automatically.

**Comment by westhom** [comment]
I have not disabled the file compiler.

**Comment by aw73** [comment]
Same result width ProcessWire 3.0.61 and PHP 7.1.4

**Comment by LostKobrakai** [comment]
Should be fixed with this: https://github.com/LostKobrakai/Migrations/commit/d22e6b4c5a5726e320dae0f6bd586578ad19a3b7
