### ISSUE TITLE
Multisite and Broken Paths

### ISSUE THREAD

**Issue by ethanbeyer** [LostKobrakai/Migrations#18]
Hey,

I am starting a multi-site build (using `index.config.php` in the root, resulting in `/site-a`, `/site-b`, etc), and I found an error with this module:

[Migrations.module:L296](https://github.com/LostKobrakai/Migrations/blob/master/Migrations.module#L296) reads: `$this->path = $this->config->paths->root . "site/migrations/";`,

but it should be `$this->path = $this->config->paths->site . "migrations/";` in order to account for a site directory that is NOT named `site`.

**Comment by ethanbeyer** [comment]
Would you like me to open this as a pull request?

**Comment by LostKobrakai** [comment]
That would certainly speed up things, as my free time for open source things is currently quite limited.

**Comment by ethanbeyer** [comment]
Closed by 43248f025a1fe357726ada14898c916bce0e32d9
