### ISSUE TITLE
add seconds to the timestamp of filename for more precision

### ISSUE THREAD

**Issue by jlahijani** [LostKobrakai/Migrations#2]
Right now, the file names are labeled like so:
Y-m-d_H-i

If you create 2 migrations within it a minute, you'll get the error stating:
"There's already a file existing for the current time."

Why not add seconds so it can be a little more precise while also preventing that race condition from occurring?

Y-m-d_H-i-s

**Comment by LostKobrakai** [comment]
I'm already using the module for a few month and really the only time this was a issue is now when playing around with the module for testing purposes. I'll keep it in my head until I have a good way to handle my own legacy migrations (or maybe just rename them with …-00).

**Comment by LostKobrakai** [comment]
Seconds are not optional and new migrations are created with seconds.
