### ISSUE TITLE
Warning: "continue" targeting switch is equivalent to "break" in AccessMigration.php on line 81

### ISSUE THREAD

**Issue by clsource** [LostKobrakai/Migrations#23]
Hello, upon installing the module It showed a warning.

- ProcessWire 3.0.148
- PHP 7.3

` Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/site/modules/Migrations/classes/AccessMigration.php on line 81`

https://github.com/LostKobrakai/Migrations/blob/master/classes/AccessMigration.php#L81

```php
switch ($type) {
    case 'view':
    case 'edit':
    case 'add':
    case 'create':
        $types = [$type];
        break;
    case 'full':
        $types = ['view', 'edit', 'create', 'add'];
        break;
    default:
        continue;
}
```

I'm not sure if this should be solved by changing `continue` to `break` or adding `continue 2`. It would depend by the desired behaviour.

**More Info**

https://www.php.net/manual/en/control-structures.continue.php

Note: In PHP the switch statement is considered a looping structure for the purposes of continue. continue behaves like break (when no arguments are passed) but will raise a warning as this is likely to be a mistake. If a switch is inside a loop, continue 2 will continue with the next iteration of the outer loop. 

I solved it by using this code.

```php
foreach ($commands as $command) {
    $type = $this->getName($command);
    
    $types = [];

    switch ($type) {
        case 'view':
        case 'edit':
        case 'add':
        case 'create':
            $types = [$type];
            break;
        case 'full':
            $types = ['view', 'edit', 'create', 'add'];
            break;
        default:
            break;
    }
...
```

**Comment by LostKobrakai** [comment]
`continue 2;` is the correct behaviour. If there's no valid type there's no need to continue with the command.

**Comment by clsource** [comment]
Thanks 👍
