### ISSUE TITLE
support for migration of forms (FormBuilder module)

### ISSUE THREAD

**Issue by jlahijani** [LostKobrakai/Migrations#3]
FormBuilder has the ability to export and import forms.  It would be interesting if this module could also migrate forms.  Something to think about either short or long term.

**Comment by LostKobrakai** [comment]
I'm not so keep about adding to many Migration variants. By now it's simply this to create such a form (skipping all data validity checks, which should not be needed in migrations).

``` php
$form = $this->forms->addNew($formName);
$form->roles = $roles; 
$form->save();

if(!$this->forms->importJSON($form->id, $json)) throw new WireException($this->_('Error importing form data'));
```

**Comment by LostKobrakai** [comment]
What I would be fine with is actually having a community examples/snippets repository, where migration snippets for various tasks (like above) could be submitted by pull-request. What would you think about that?
