### ISSUE TITLE
support for migration of hannacodes (TextformatterHannaCode module)

### ISSUE THREAD

**Issue by jlahijani** [LostKobrakai/Migrations#4]
Hanna Code has the ability to export and import hannacodes.  It would be interesting if this module could also migrate them.  Something to think about either short or long term.

**Comment by LostKobrakai** [comment]
Same answer as here: https://github.com/LostKobrakai/Migrations/issues/3 
But hanna code doesn't actually have a nice import function – often a issue with being to lazy to create a separate module and process module, was the same with this one until this week – Maybe someone could extract the import process out to a separate function and add a pull-request to the module, so the import is usable without a form submitting the data.
