### ISSUE TITLE
.gitattributes and ignores

### ISSUE THREAD

**Issue by jlahijani** [LostKobrakai/Migrations#6]
When downloading the installing the module, it currently brings the sample files inside the 'migrations' folder with it.  Perhaps these could be left in the repo, but not actually downloaded when checking out the module.

This can be done using .gitattributes

Good example:
https://github.com/mpdf/mpdf/blob/development/.gitattributes

**Comment by LostKobrakai** [comment]
I don't really like that the "Download ZIP" archive here on github does miss these files as well, though I'll give it a thought.

**Comment by LostKobrakai** [comment]
With adding the docs folder this finally made sense. Not docs and example migrations are not part of the export.
